#!/bin/bash

for net in fc_base fc_1 fc_2 fc_3 fc_4 fc_5 fc_6 fc_7 conv_base conv_1 conv_2 conv_3 conv_4; do
	echo Evaluating network ${net}...
	for path in test_cases/"$net"/*.txt; do
		echo "$path"
		python src/verifier.py --net ${net} --spec "$path" --check
	done
done
